[2024-06-03T22:07:19.518-0500] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-03T22:07:19.605-0500] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: python_pipeline.group_by_smoke manual__2024-06-04T03:07:10.911587+00:00 [queued]>
[2024-06-03T22:07:19.613-0500] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: python_pipeline.group_by_smoke manual__2024-06-04T03:07:10.911587+00:00 [queued]>
[2024-06-03T22:07:19.614-0500] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-03T22:07:19.632-0500] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): group_by_smoke> on 2024-06-04 03:07:10.911587+00:00
[2024-06-03T22:07:19.636-0500] {standard_task_runner.py:63} INFO - Started process 44575 to run task
[2024-06-03T22:07:19.639-0500] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'python_pipeline', 'group_by_smoke', 'manual__2024-06-04T03:07:10.911587+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/data_cleaning.py', '--cfg-path', '/tmp/tmp72h3o4j2']
[2024-06-03T22:07:19.640-0500] {standard_task_runner.py:91} INFO - Job 55: Subtask group_by_smoke
[2024-06-03T22:07:19.679-0500] {task_command.py:426} INFO - Running <TaskInstance: python_pipeline.group_by_smoke manual__2024-06-04T03:07:10.911587+00:00 [running]> on host diallo
[2024-06-03T22:07:19.752-0500] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Diallo' AIRFLOW_CTX_DAG_ID='python_pipeline' AIRFLOW_CTX_TASK_ID='group_by_smoke' AIRFLOW_CTX_EXECUTION_DATE='2024-06-04T03:07:10.911587+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-04T03:07:10.911587+00:00'
[2024-06-03T22:07:19.753-0500] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-03T22:07:19.765-0500] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-03T22:07:19.766-0500] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/diallo/airflow/dags/data_cleaning.py", line 45, in group_by_smoke
    json_data = ti.xcom_pull(task_id='clean_data')
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
TypeError: TaskInstance.xcom_pull() got an unexpected keyword argument 'task_id'
[2024-06-03T22:07:19.771-0500] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=python_pipeline, task_id=group_by_smoke, run_id=manual__2024-06-04T03:07:10.911587+00:00, execution_date=20240604T030710, start_date=20240604T030719, end_date=20240604T030719
[2024-06-03T22:07:19.786-0500] {standard_task_runner.py:110} ERROR - Failed to execute job 55 for task group_by_smoke (TaskInstance.xcom_pull() got an unexpected keyword argument 'task_id'; 44575)
[2024-06-03T22:07:19.811-0500] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-03T22:07:19.823-0500] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-03T22:07:19.823-0500] {local_task_job_runner.py:222} INFO - ::endgroup::
