[2024-06-03T22:33:26.778-0500] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-03T22:33:26.859-0500] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: python_pipeline.group_by_region manual__2024-06-04T03:31:54.985380+00:00 [queued]>
[2024-06-03T22:33:26.865-0500] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: python_pipeline.group_by_region manual__2024-06-04T03:31:54.985380+00:00 [queued]>
[2024-06-03T22:33:26.865-0500] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-03T22:33:26.888-0500] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): group_by_region> on 2024-06-04 03:31:54.985380+00:00
[2024-06-03T22:33:26.894-0500] {standard_task_runner.py:63} INFO - Started process 45742 to run task
[2024-06-03T22:33:26.899-0500] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'python_pipeline', 'group_by_region', 'manual__2024-06-04T03:31:54.985380+00:00', '--job-id', '155', '--raw', '--subdir', 'DAGS_FOLDER/data_cleaning.py', '--cfg-path', '/tmp/tmp4o1aqfef']
[2024-06-03T22:33:26.901-0500] {standard_task_runner.py:91} INFO - Job 155: Subtask group_by_region
[2024-06-03T22:33:26.940-0500] {task_command.py:426} INFO - Running <TaskInstance: python_pipeline.group_by_region manual__2024-06-04T03:31:54.985380+00:00 [running]> on host diallo
[2024-06-03T22:33:27.011-0500] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Diallo' AIRFLOW_CTX_DAG_ID='python_pipeline' AIRFLOW_CTX_TASK_ID='group_by_region' AIRFLOW_CTX_EXECUTION_DATE='2024-06-04T03:31:54.985380+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-04T03:31:54.985380+00:00'
[2024-06-03T22:33:27.011-0500] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-03T22:33:27.030-0500] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-03T22:33:27.031-0500] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/diallo/airflow/dags/data_cleaning.py", line 63, in group_by_region
    df = pd.read_json(json_data)
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/pandas/io/json/_json.py", line 791, in read_json
    json_reader = JsonReader(
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/pandas/io/json/_json.py", line 904, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/pandas/io/json/_json.py", line 944, in _get_data_from_filepath
    self.handles = get_handle(
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/pandas/io/common.py", line 728, in get_handle
    ioargs = _get_filepath_or_buffer(
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/pandas/io/common.py", line 472, in _get_filepath_or_buffer
    raise ValueError(msg)
ValueError: Invalid file path or buffer object type: <class 'NoneType'>
[2024-06-03T22:33:27.036-0500] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=python_pipeline, task_id=group_by_region, run_id=manual__2024-06-04T03:31:54.985380+00:00, execution_date=20240604T033154, start_date=20240604T033326, end_date=20240604T033327
[2024-06-03T22:33:27.051-0500] {standard_task_runner.py:110} ERROR - Failed to execute job 155 for task group_by_region (Invalid file path or buffer object type: <class 'NoneType'>; 45742)
[2024-06-03T22:33:27.070-0500] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-03T22:33:27.090-0500] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-03T22:33:27.091-0500] {local_task_job_runner.py:222} INFO - ::endgroup::
